### ISSUE TITLE
纵向任务报错

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#122]
2023-05-22 11:06:11,749 platform=FL INFO 1 taskid=1660467895098421250 primihub.utils.logger_util <string>:1722:host_tree_construct current role: guest, current record: 6
W20230522 11:06:50.569720 13644 thread_pool.h:135] Thread pool queue has reached maximum size. Increasing to 204800000 tasks.
E20230522 11:06:57.812204 10686 node.cc:698] task execute encountes error, begin to kill task to release resource
E20230522 11:06:57.812407 10686 node.cc:704] party info: defalut:172.28.1.10:50050:0:default
I20230522 11:06:57.813480 13870 node.cc:506] receive request for kill task for:  job_id: 1 task id: 1660467895098421250 from SCHEDULER
W20230522 11:06:57.813531 13870 task.h:47] task receives kill task request and stop stauts
E20230522 11:06:57.813560 13870 task_context.h:93] stop all in data queue
E20230522 11:06:57.813599 13870 task_context.h:100] stop all out data queue
E20230522 11:06:57.813624 13870 task_context.h:107] stop all complete queue
E20230522 11:06:57.813644 13870 node.cc:539] end of VMNodeImpl::KillTask
E20230522 11:06:57.814442 10686 node.cc:704] party info: defalut:172.28.1.11:50051:0:default
2023-05-22 11:06:57.820 | ERROR    | primihub.executor:execute_py:79 - Exception: 
self.log_level:  20
2023-05-22 11:06:57.820 | ERROR    | primihub.executor:execute_py:79 - Exception: 
E20230522 11:06:57.822094 10687 py_executor.cc:240] Failed to execute python: ValueError: received data encountes error

At:
  <string>(843): recv
  <string>(1615): host_tree_construct
  <string>(1743): host_tree_construct
  <string>(1743): host_tree_construct
  <string>(1743): host_tree_construct
  <string>(1743): host_tree_construct
  <string>(1743): host_tree_construct
  <string>(1944): fit
  <string>(2166): xgb_host_logic
  /usr/local/lib/python3.8/dist-packages/primihub/executor.py(84): execute_py
E20230522 11:06:58.098129 10684 fl_task.cc:74] begin to terminate py_main
I20230522 11:06:58.226557 10684 fl_task.cc:85] py_main executes result code: 383

**Comment by xuefeng-xu** [comment]
@LindaHu0701 你好，另一个节点的日志麻烦也发下

**Comment by LindaHu0701** [comment]
这是另一个节点的日志

2023-05-22T03:06:53.919798865Z 2023-05-22 11:06:53.915 | ERROR    | primihub.executor:execute_py:79 - Exception: 
2023-05-22T03:06:53.920116420Z ============== Index(['cos_theta_r1', 'dPhi_r_b'], dtype='object') [[GroupedDataset(dataset=Dataset(num_blocks=1, num_rows=269106, schema={cos_theta_r1: float64, g: object}), key='cos_theta_r1'), GroupedDataset(dataset=Dataset(num_blocks=1, num_rows=269106, schema={dPhi_r_b: float64, g: object}), key='dPhi_r_b')]] 1
2023-05-22T03:06:53.920136891Z 2023-05-22 11:06:53.915 | ERROR    | primihub.executor:execute_py:79 - Exception: 
2023-05-22T03:06:53.935238318Z E20230522 11:06:53.930652  4504 py_executor.cc:240] Failed to execute python: RayActorError: The actor died unexpectedly before finishing this task.
2023-05-22T03:06:53.935266925Z 	class_name: GroupPool
2023-05-22T03:06:53.935271750Z 	actor_id: 234857a2cc312ee4979f903701000000
2023-05-22T03:06:53.935275378Z 	pid: 5990
2023-05-22T03:06:53.935279231Z 	namespace: 4940da66-4203-455a-a567-2216085e6790
2023-05-22T03:06:53.935282247Z 	ip: 172.28.1.11
2023-05-22T03:06:53.935285161Z The actor is dead because its worker process has died. Worker exit type: NODE_OUT_OF_MEMORY Worker exit detail: Task was killed due to the node running low on memory.
2023-05-22T03:06:53.935289389Z 
2023-05-22T03:06:53.935292562Z Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
2023-05-22T03:06:53.935296689Z 
2023-05-22T03:06:53.935299469Z At:
2023-05-22T03:06:53.935302114Z   /usr/local/lib/python3.8/dist-packages/ray/_private/worker.py(2330): get
2023-05-22T03:06:53.935304835Z   /usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py(105): wrapper
2023-05-22T03:06:53.935319153Z   /usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py(218): get_next
2023-05-22T03:06:53.935323500Z   /usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py(83): map
2023-05-22T03:06:53.935327355Z E20230522 11:06:53.935106  4504 py_executor.cc:273] py executor encoutes error when executing task
2023-05-22T03:06:56.659820547Z Traceback (most recent call last):
2023-05-22T03:06:56.659877109Z   File "/usr/local/lib/python3.8/dist-packages/primihub/executor.py", line 63, in execute_py
2023-05-22T03:06:56.659888980Z     func()
2023-05-22T03:06:56.659897614Z   File "<string>", line 2406, in xgb_guest_logic
2023-05-22T03:06:56.659906695Z   File "<string>", line 1232, in fit
2023-05-22T03:06:56.659915335Z   File "<string>", line 1212, in guest_tree_construct
2023-05-22T03:06:56.659923254Z   File "<string>", line 1212, in guest_tree_construct
2023-05-22T03:06:56.659931734Z   File "<string>", line 1212, in guest_tree_construct
2023-05-22T03:06:56.659965168Z   [Previous line repeated 2 more times]
2023-05-22T03:06:56.659973174Z   File "<string>", line 1104, in guest_tree_construct
2023-05-22T03:06:56.659981057Z   File "<string>", line 1014, in sums_of_encrypted_ghs_with_ray
2023-05-22T03:06:56.659990215Z   File "/usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py", line 83, in map
2023-05-22T03:06:56.659999372Z     yield self.get_next()
2023-05-22T03:06:56.660007327Z   File "/usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py", line 218, in get_next
2023-05-22T03:06:56.660016246Z     return ray.get(future)
2023-05-22T03:06:56.660074167Z   File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
2023-05-22T03:06:56.660083192Z     return func(*args, **kwargs)
2023-05-22T03:06:56.660092113Z   File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2311, in get
2023-05-22T03:06:56.660104953Z     raise value
2023-05-22T03:06:56.660112664Z ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2023-05-22T03:06:56.660120751Z 	class_name: GroupPool
2023-05-22T03:06:56.660128565Z 	actor_id: 234857a2cc312ee4979f903701000000
2023-05-22T03:06:56.660136186Z 	pid: 5990
2023-05-22T03:06:56.660143406Z 	namespace: 4940da66-4203-455a-a567-2216085e6790
2023-05-22T03:06:56.660151900Z 	ip: 172.28.1.11
2023-05-22T03:06:56.660160524Z The actor is dead because its worker process has died. Worker exit type: NODE_OUT_OF_MEMORY Worker exit detail: Task was killed due to the node running low on memory.
2023-05-22T03:06:56.660169641Z 
2023-05-22T03:06:56.660177891Z Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
2023-05-22T03:06:57.808668457Z I20230522 11:06:57.807449  4503 fl_task.cc:85] py_main executes result code: 255
2023-05-22T03:06:57.809709009Z E20230522 11:06:57.808806  4503 worker.cc:57] Error occurs during execute task.
2023-05-22T03:06:57.815709158Z I20230522 11:06:57.815413  9118 node.cc:506] receive request for kill task for:  job_id: 1 task id: 1660467895098421250 from SCHEDULER
2023-05-22T03:06:57.815728169Z W20230522 11:06:57.815454  9118 node.cc:517] worker for job id: 1 task id: 1660467895098421250 request id: 1660467895186501634 has finished

**Comment by xuefeng-xu** [comment]
@LindaHu0701 谢谢，看起来是使用ray的时候内存溢出了，我们近期将会修复这个。

**Comment by fuxingbit** [comment]
你部署的这个机器内存多大？

**Comment by LindaHu0701** [comment]
内存128G

**Comment by fuxingbit** [comment]
docker-compose.yaml 里node0/1/2 有这个配置，把这个配置调整到大于内存的30%试一下
```
  node0:
    shm_size: '6gb'  # ray's request,more than RAM 30% 
```

**Comment by LindaHu0701** [comment]
加入这个配置仍然不行，等修复之后我再试试

**Comment by xuefeng-xu** [comment]
@LindaHu0701 可以告诉我们怎么复现这个bug吗？

**Comment by LindaHu0701** [comment]
应该是我用的数据集比较大，分别有79.6 MB和10.2MB，没有跑通过。
之前我用7.96 MB和1.02MB，有时候会报这个错误，有时候能跑通

**Comment by LindaHu0701** [comment]
应该是我用的数据集比较大，分别有79.6 MB和10.2MB，没有跑通过。
之前我用7.96 MB和1.02MB，有时候会报这个错误，有时候能跑通

**Comment by xuefeng-xu** [comment]
@LindaHu0701 应该不是文件大小的原因，我们用过更大的数据。方便给几条数据的例子吗，我们这边测试下。

**Comment by xuefeng-xu** [comment]
@LindaHu0701 你们的数据类型是什么样的（数值型，字符型或其他），样本数量和特征维度分别是多少
