### ISSUE TITLE
Failed to run webconsole

### ISSUE THREAD

**Issue by 271983592** [primihub/primihub-platform#69]
I installed the latest version nodejs and wanted to build primihub-webconsole. I encountered some error messages as below. Please help me, thanks.

npm run dev --port=9528

> privacy-platform@1.0.0 dev
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
    at module.exports.tap (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/webpack-chain/src/Plugin.js:26:15)
    at chainWebpack (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/vue.config.js:72:30)
    at /home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at Service.resolveWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:272:48)
    at PluginAPI.resolveWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/commands/serve.js:79:31)
    at Service.run (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Zjj614** [comment]
you can degrade nodejs to 16.18.1 and run npm run dev --port=9528 again.
it works to me.

**Comment by 271983592** [comment]
Thanks for you reply. I installed nodejs of 16.18.1 and found the errors as follow:

node --version
v16.18.1

npm --version
8.19.2

npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/cli-plugin-eslint@5.0.8
npm ERR! Found: eslint@6.7.2
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"6.7.2" from the root project
npm ERR!   peer eslint@">= 4.12.1" from babel-eslint@10.1.0
npm ERR!   node_modules/babel-eslint
npm ERR!     dev babel-eslint@"10.1.0" from the root project
npm ERR!   2 more (eslint-plugin-vue, vue-eslint-parser)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=7.5.0" from @vue/cli-plugin-eslint@5.0.8
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^5.0.8" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.29.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">=7.5.0" from @vue/cli-plugin-eslint@5.0.8
npm ERR!   node_modules/@vue/cli-plugin-eslint
npm ERR!     dev @vue/cli-plugin-eslint@"^5.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/songxm/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/songxm/.npm/_logs/2022-12-03T13_02_05_889Z-debug-0.log

**Comment by Zjj614** [comment]
peerDependenciesMeta used in @vue/cli-service causes unexpected behavior on npm 7.
run:
npm install --legacy-peer-deps

if it not works, you can remove node_modules folder and repeat above directive.

**Comment by 271983592** [comment]
I first run the command of "npm install --legacy-peer-deps" and it works.
But I continued to execute "npm run dev --port=9528" and the error came as follow:

> privacy-platform@1.0.0 dev
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
    at Object.tap (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/webpack-chain/src/Plugin.js:26:15)
    at chainWebpack (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/vue.config.js:72:30)
    at /home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at Service.resolveWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:272:48)
    at PluginAPI.resolveWebpackConfig (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/commands/serve.js:79:31)
    at Service.run (/home/songxm/devel/github/1125/primihub-platform/primihub-webconsole/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by fuxingbit** [comment]
Please refer to the environment run in Dockerfile.local

**Comment by 271983592** [comment]
Thanks. For some reasons, my local configuration package.json has been changed. I rebuild the latest code from github and the previous problem I have is solved.
